### ISSUE TITLE
Observatório #1: The Fast and the Furious

### ISSUE THREAD

**Issue by cmilfont** [produtoreativo/observatorio#1]
Primeiro episódio, vamos ver se a série será tão longa quanto a fabulosa franquia [The Fast and the Furious](https://en.wikipedia.org/wiki/The_Fast_and_the_Furious_(2001_film))

**Comment by cmilfont** [comment]
[Codecov OpenSource](https://about.codecov.io/blog/codecov-is-now-open-source/), umas das melhoes ferramentas para qualidade agora seguindo o modelo da nave mãe, Sentry.
Para quem não sabe o Sentry sempre foi OpenSource e SaaS, muita gente não gosta de manter On-prem e faz todo o sentido, toda ferramenta é linda quando é gerenciada e parece cozinha de restaurante, melhor não olhar por dentro.

**Comment by cmilfont** [comment]
Interessante como este post apareceu em dezenas de Clipping num alerta que criei sobre Observability: [Observabilidade: Uma Ferramenta Essencial para o Desenvolvimento do Negócio](https://www.segs.com.br/seguros/381126-observabilidade-uma-ferramenta-essencial-para-o-desenvolvimento-do-negocio).
Artigo bem escrito que já demostra que o mercado entendeu que Observabilidade não é a mesma coisa que monitoria.

**Comment by cmilfont** [comment]
Aproveitando o tema de [monitoria vs observabilidade](https://www.linkedin.com/posts/elvenworks_monitoramento-x-observabilidade-qual-a-diferen%C3%A7a-activity-7041495076102881280-mAPG?utm_source=share&utm_medium=member_desktop), a ElvenWorks, nosso parceiro, tem um Bootcamp bastante maduro que foca bastante nas boas práticas completas, fala há bastante tempo sobre isso e recentemente lançou o [Canvas de Observabilidade](https://www.linkedin.com/feed/update/urn:li:activity:7041463927573995520?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7041463927573995520%29).

**Comment by cmilfont** [comment]
Neste episódio eu trarei uma abordagem prática sobre o tema [MELT (Métricas, eventos, logs e traces)](https://www.linkedin.com/pulse/future-observability-melt-wayne-howard/).
Dividido em duas seções, uma estratégicas para líderes e demais papeis do time e uma mão na massa para técnicos.

**Comment by cmilfont** [comment]
Tenho visto várias vagas como esta [Engenheiro de Observabilidade Pleno (DataDog)](https://www.works.so/remote-jobs/engenheiro-de-observabilidade-pleno-datadog-pperyazpxnpnrtboovnqdrraly)
Ao primeiro olhar não tem nada demais, acredito que é este escopo mesmo que um Senior precisa cobrir, mas pensando um pouco, quantos profissionais temos no mercado que preencheria estes quesitos?
Falemos um pouco sobre competências!

**Comment by cmilfont** [comment]
> Tenho visto várias vagas como esta [Engenheiro de Observabilidade Pleno (DataDog)](https://www.works.so/remote-jobs/engenheiro-de-observabilidade-pleno-datadog-pperyazpxnpnrtboovnqdrraly) Ao primeiro olhar não tem nada demais, acredito que é este escopo mesmo que um Senior precisa cobrir, mas pensando um pouco, quantos profissionais temos no mercado que preencheria estes quesitos? Falemos um pouco sobre competências!

Esta vaga aqui é bem mais sinistra: [Pessoa Analista SRE (Observabilidade) Sênior](https://remotar.com.br/job/21798/dqr-tech/pessoa-analista-sre-(observabilidade)-senior)

**Comment by cmilfont** [comment]
> Aproveitando o tema de [monitoria vs observabilidade](https://www.linkedin.com/posts/elvenworks_monitoramento-x-observabilidade-qual-a-diferen%C3%A7a-activity-7041495076102881280-mAPG?utm_source=share&utm_medium=member_desktop), a ElvenWorks, nosso parceiro, tem um Bootcamp bastante maduro que foca bastante nas boas práticas completas, fala há bastante tempo sobre isso e recentemente lançou o [Canvas de Observabilidade](https://www.linkedin.com/feed/update/urn:li:activity:7041463927573995520?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7041463927573995520%29).

Link para os Slides do [Canvas de Observabilidade](https://docs.google.com/presentation/d/1u-b7KR1J8MHqlnhOY7f54HYkXwAu9Mhs79U0ZqkLfvo/edit#slide=id.g1dfd739bb76_0_333)

**Comment by cmilfont** [comment]
Falando sobre métricas, um post sensacional sobre Frameworks consolidades de métricas para guiar (em inglês): [Product Managers’ Guide for Selecting the Right Product Metrics Framework](https://userpilot.medium.com/product-managers-guide-for-selecting-the-right-product-metrics-framework-def86c43c3c9)

**Comment by barroso** [comment]
Montei esse diagrama buscando criar uma visão clara do processo de desenvolvimento  de produto, a ideia é colocar informações, processos e tarefas  em um formato didático.

![ProductDevelopmentCycle](https://github.com/produtoreativo/observatorio/assets/71138/8768b72f-7728-4045-a4f9-5bda4a401d30)

Problemas recorrente que encontro nos times:
- Silos: Devs conversam pouco com outras áreas, design e produto.
- Falta de ferramentas que monitorem o produto em produção, seja para suporte, análise ou performance.
- Taks chegando para o time de desenvolvimento sem contexto, muitas vezes conversamos com os devs e eles relatam que não conhecem objetivo da task.
- Muitas vezes o time pensa que o dono do backlog é o PM, existe um papel de gatekeeper mas qualquer pessoa pode solicitar ou incluir novas tasks no backlog.

@cmilfont sei que os tópicos parecem uma verdadeira "salada", qualquer coisa me avisa que organizo melhor minhas ideias!

**Comment by samuelteixeiras** [comment]
Nao sei se esta nos planos de falar sobre:  https://opentelemetry.io/

**Comment by cmilfont** [comment]
> Nao sei se esta nos planos de falar sobre: https://opentelemetry.io/

Comentei um pouco no episodio, mas pretendo trazer com foco em outro episódio, só sobre OPTEL

**Comment by cmilfont** [comment]
Um livro que saiu ano passado e é gratuito disponibilizado pela [Honeycomb](https://info.honeycomb.io/observability-engineering-oreilly-book-2022).
Muito bom, quem não consegue ler em inglês, usa o translator, chatGPT, mas não deixa de ler com bastante calma.

**Comment by cmilfont** [comment]
Vaga interessante https://boards.greenhouse.io/github/jobs/5265217

**Comment by fclesio** [comment]
Existe o [Awesomely Observability](https://github.com/adriannovegil/awesome-observability) que tem uma estrutura de tópicos interessante mas é muito focado em ferramentas.

**Comment by cmilfont** [comment]
Pessoal, retomando esse projeto
https://www.youtube.com/watch?v=oCrLhAkjDCY

Acabei adaptando e fazendo um resumo para os temas de agora e abrindo mais
